# permissions for end users to edit brooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: broom-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: broom
    app.kubernetes.io/part-of: broom
    app.kubernetes.io/managed-by: kustomize
  name: broom-editor-role
rules:
- apiGroups:
  - ai.m3.com
  resources:
  - brooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.m3.com
  resources:
  - brooms/status
  verbs:
  - get
