apiVersion: ai.m3.com/v1alpha1
kind: Broom
metadata:
  labels:
    app.kubernetes.io/name: broom
    app.kubernetes.io/instance: broom-sample
    app.kubernetes.io/part-of: broom
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: broom
  name: broom-sample
spec:
  target:
    # name: oom-sample
    labels:
      m3.com/use-broom: "true"
    # namespace: broom
  adjustment:
    type: Mul
    value: "2"
    maxLimit: "250Mi"
  restartPolicy: "OnSpecChanged"
  slackWebhook:
    secret:
      namespace: default
      name: broom
      key: SLACK_WEBHOOK_URL
    # channel: "#alert"
